services:
  - type: web
    name: edit-me-backend
    env: node
    region: oregon # or choose a region closer to your users
    plan: free
    nodeVersion: 18.19.1
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PUSHER_APP_ID
        value: "1998026"
      - key: PUSHER_KEY
        value: "8bd2ea2900117f155976"
      - key: PUSHER_SECRET
        value: "50a68da6917f27b37f6e"
      - key: PUSHER_CLUSTER
        value: "ap2"
    healthCheckPath: /api/health
    autoDeploy: true 